function  emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)
Fig=figure('Name','Pop Catalin-Cornel',...
           'Units','normalized',...
           'Position',[0.10 0.1 0.83 0.80]);

%formulele necesare circuitului

       VBB=(RB2/(RB1+RB2))*VAl;
       VBE=0.6;
       IE=((VBB-VBE)/RE);
       IC=IE;
       vCE=VAl-IC*(RC+RE); 
       RB=RB1*RB2/(RB1+RB2);
       
       Ro=RC;
       gm=40.*IC;
       rbe=beta/gm;
       Ri=RB*rbe/(RB+rbe);
       Avi=-gm*RC;
      
      

%plotarea imaginilor
subplot(2,2,1);
image(imread("C:\Users\XMarius\Desktop\facultate\AN 2 SEM 1\GAC\PROIECT\Pop Catalin-2126\poze\Circuit complet.png"));
title('Conexiunea emitor comun')
set(gca,'xtick',[]);
set(gca,'ytick',[]);

    
CC=uicontrol( ...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.22 0.08 0.15 0.05],...
        'Fontsize', 12,...
        'String','Circuit Curent Continuu',...
        'Callback','imshow(imread("C:\Users\XMarius\Desktop\facultate\AN 2 SEM 1\GAC\PROIECT\Pop Catalin-2126\poze\circuit in cc.png"))');
SM=uicontrol( ...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.22 0.03 0.15 0.05],...
        'Fontsize', 12,...
        'String','Circuit semnal mic',...
        'Callback','imshow(imread("C:\Users\XMarius\Desktop\facultate\AN 2 SEM 1\GAC\PROIECT\Pop Catalin-2126\poze\sm.png"))');
circuit=uicontrol( ...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.22 0.13 0.15 0.05],...
        'Fontsize', 12,...
        'String','Circuit complet',...
        'Callback','imshow(imread("C:\Users\XMarius\Desktop\facultate\AN 2 SEM 1\GAC\PROIECT\Pop Catalin-2126\poze\Circuit complet.png"))');
%popup meniul cu tipurile de semnale
 Bp=uicontrol('style','popup',...
           'units','normalized',...
           'position',[0.75 0.85 0.2 0.1],...
           'value',tip,...
           'FontSize',14,...
           'string','Semnal Sinusoidal|Semnal Cosinus|Semnal Triunghiular Sinus |Semnal Triunghiular Cosinus|Semnal dinte de Fierastrau',...
           'callback','tip=get(gco,''value'');close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)');
   %tipurile de semnale 
     T=1/f;
     t=0:T/100:N*T;
       
      switch(tip)
     case 1
        vi=A.*sin(2.*pi.*f.*t);
    case 2
        vi=A.*cos(2.*pi.*f.*t);
    case 3
        vi=(2.*A./pi)*asin(sin(2.*pi.*f.*t));
    case 4
        vi=(2.*A./pi)*asin(cos(2.*pi.*f.*t)); 
    case 5
        vi=(2.*A./pi)*atan(tan(2.*pi.*f.*t./2));
    
      end 
%vo pt semnal mic
    vo=vi.*Avi;
    %vo pentru DC
    a=ones(size(t));
     VO = VAl - IC*RC;
    vdc=ones(size(t))*VO;
    %Vo ul pt semnal mic si DC
       v = vi.*Avi
       vO =VO - (-1* v);
       v0= A*Avi;

%gruparea butoanelor
RadioGroup=uibuttongroup('Visible','on',...
'BackgroundColor',[1,1,1],...
'ForegroundColor','black',...
'Title','Date de intrare:',...
'FontSize',10,...
'TitlePosition','centertop',...
'Position',[0.35 0.2 0.2 0.35]);

%datele de intrare text

Bt2=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.85 0.3 0.05],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','A (V)',... 
    'Parent',RadioGroup); 

Bt3=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.75 0.3 0.05],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','f (hz)',... 
    'Parent',RadioGroup);

Bt4=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.65 0.3 0.05],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','N',... 
    'Parent',RadioGroup);

Bt5=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.55 0.3 0.05],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','RB1 (Kohm)',... 
    'Parent',RadioGroup); 

Bt6=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.45 0.3 0.05],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','RB2 (Kohm)',... 
    'Parent',RadioGroup); 

Bt7=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.35 0.3 0.05],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','RE (Kohm)',... 
    'Parent',RadioGroup); 

Bt8=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.25 0.3 0.05],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','beta',... 
    'Parent',RadioGroup); 

Bt9=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.15 0.3 0.05],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','RC (Kohm)',... 
    'Parent',RadioGroup);

Bt10=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.05 0.3 0.05],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','VAl (V)',... 
    'Parent',RadioGroup);

%butoane de edit pentru datele de intrare
   
Be2=uicontrol('Style','edit',...  
    'Units','normalized',...             
    'Position',[0.6 0.85 0.3 0.05],...     
    'foregroundcolor','black',...            
    'String',A,...            
    'Callback','A=str2num(get(gco,''String'')),close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)',...
    'Parent',RadioGroup);
   
Be3=uicontrol('Style','edit',...  
    'Units','normalized',...             
    'Position',[0.6 0.75 0.3 0.05],...     
    'foregroundcolor','black',...            
    'String',f,...            
    'Callback','f=str2num(get(gco,''String'')),close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)',...
    'Parent',RadioGroup);
     
Be4=uicontrol('Style','edit',...  
    'Units','normalized',...             
    'Position',[0.6 0.65 0.3 0.05],...     
    'foregroundcolor','black',...            
    'String',N,...            
    'Callback','N=str2num(get(gco,''String'')),close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)',...
    'Parent',RadioGroup);

Be5=uicontrol('Style','edit',...  
    'Units','normalized',...             
    'Position',[0.6 0.55 0.3 0.05],...     
    'foregroundcolor','black',...            
    'String',RB1,...            
    'Callback','RB1=str2num(get(gco,''String'')),close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)',...
    'Parent',RadioGroup);

Be6=uicontrol('Style','edit',...  
    'Units','normalized',...             
    'Position',[0.6 0.45 0.3 0.05],...     
    'foregroundcolor','black',...            
    'String',RB2,...            
    'Callback','RB2=str2num(get(gco,''String'')),close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)',...
    'Parent',RadioGroup);

Be7=uicontrol('Style','edit',...  
    'Units','normalized',...             
    'Position',[0.6 0.35 0.3 0.05],...     
    'foregroundcolor','black',...            
    'String',RE,...            
    'Callback','RE=str2num(get(gco,''String'')),close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)',...
    'Parent',RadioGroup);

Be8=uicontrol('Style','edit',...  
    'Units','normalized',...             
    'Position',[0.6 0.25 0.3 0.05],...     
    'foregroundcolor','black',...            
    'String',beta,...            
    'Callback','beta=str2num(get(gco,''String'')),close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)',...
    'Parent',RadioGroup);

Be9=uicontrol('Style','edit',...  
    'Units','normalized',...             
    'Position',[0.6 0.15 0.3 0.05],...     
    'foregroundcolor','black',...            
    'String',RC,...            
    'Callback','RC=str2num(get(gco,''String'')),close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)',... 
    'Parent',RadioGroup);

Be10=uicontrol('Style','edit',...  
    'Units','normalized',...             
    'Position',[0.6 0.05 0.3 0.05],...     
    'foregroundcolor','black',...            
    'String',VAl,...            
    'Callback','VAl=str2num(get(gco,''String'')),close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)',...
    'Parent',RadioGroup);
%parametri semnal mic%
RadioGroup1=uibuttongroup('Visible','on',...
'BackgroundColor',[1,1,1],...
'ForegroundColor','black',...
'Title','PARAMETRII SEMNAL MIC:',...
'FontSize',10,...
'TitlePosition','centertop',...
'Position',[0.07 0.2 0.17 0.3]);

Bt1=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.9 0.3 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','Ri (Kohm)',... 
    'Parent',RadioGroup1); 

Bt2=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.75 0.3 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','Ro (Kohm)',... 
    'Parent',RadioGroup1); 

Bt3=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.6 0.3 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','gm (mS)',... 
    'Parent',RadioGroup1); 

Bt4=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.45 0.3 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','rbe (Kohm)',... 
    'Parent',RadioGroup1); 

Bt5=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.3 0.3 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','Avi',... 
    'Parent',RadioGroup1);

Bt6=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.15 0.3 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','vo(V)',... 
    'Parent',RadioGroup1);

Be8=uicontrol('Style','edit',...            
    'Units','normalized',...             
    'Position',[0.5 0.90 0.4 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String',Ri,... 
    'Callback','',...
    'Parent',RadioGroup1); 

Be9=uicontrol('Style','edit',...            
    'Units','normalized',...             
    'Position',[0.5 0.75 0.4 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String',Ro,...
     'Callback','RC=str2num(get(gco,''String'')),close,emitorcomun(A,f,N,RB1,RB2,RC,RE,beta,VAl,tip)',...
    'Parent',RadioGroup1); 

Be10=uicontrol('Style','edit',...            
    'Units','normalized',...             
    'Position',[0.5 0.6 0.4 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String',gm,... 
    'Parent',RadioGroup1); 

Be11=uicontrol('Style','edit',...            
    'Units','normalized',...             
    'Position',[0.5 0.45 0.4 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String',rbe,... 
    'Parent',RadioGroup1); 
Be12=uicontrol('Style','edit',...            
    'Units','normalized',...             
    'Position',[0.5 0.3 0.4 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String',Avi,... 
    'Parent',RadioGroup1); 

 Be12=uicontrol('Style','edit',...            
    'Units','normalized',...             
    'Position',[0.5 0.15 0.4 0.1],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String',v0,... 
    'Parent',RadioGroup1); 


%punctul de stationare%
RadioGroup2=uibuttongroup('Visible','on',...
'BackgroundColor',[1,1,1],...
'ForegroundColor','black',...
'Title','PUNCT DE STATIONARE:',...
'FontSize',5,...
'TitlePosition','centertop',...
'Position',[0.24 0.2 0.11 0.13]);




Bt2=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.1 0.65 0.3 0.20],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','IC (mA)',... 
    'Parent',RadioGroup2); 

Bt3=uicontrol('Style','text',...            
    'Units','normalized',...             
    'Position',[0.60 0.65 0.3 0.20],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String','vCE (V)',... 
    'Parent',RadioGroup2); 

Bt2i=uicontrol('Style','edit',...            
    'Units','normalized',...             
    'Position',[0.1 0.25 0.3 0.25],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String',IC,... 
    'Parent',RadioGroup2); 

Bt3v=uicontrol('Style','edit',...            
    'Units','normalized',...             
    'Position',[0.6 0.25 0.3 0.25],...      
    'backgroundcolor','w',...               
    'foregroundcolor','black',...          
    'String',vCE,... 
    'Parent',RadioGroup2); 

%plotarea semnalelor
     subplot('position',[0.63 0.55 0.3 0.3]);
     plot(t,vi,'k',t,vi,'r');
     grid on;
     axis on;
     title('Tensiunea de intrare');
     xlabel('timp [s]');
     ylabel('Amplitudine [ V ]');
     
     subplot('position',[0.63 0.16 0.3 0.3]);
     plot(t,vdc,t,vO);
     grid on;
     axis on;
     title('Tensiunea de iesire');
     xlabel('timp [s]');
     ylabel('Amplitudine [ V ]');
 


    